@HotelListing.Api_HostAddress = https://localhost:7185

GET {{HotelListing.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{HotelListing.Api_HostAddress}}/api/hotels

###

@id=4
GET {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}

###

POST {{HotelListing.Api_HostAddress}}/api/hotels/{id}
Content-Type: application/json
{
  "id": 4,
  "name": "Grand Plaza",
  "address": "123 Main St",
  "rating": 4.5
}

###
@id=4
DELETE {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}

###


PUT {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}
Content-Type: application/json

{
  "id": 4,
  "name": "Test Hotel",
  "address": "123 Main St",
  "rating": 4.5
}

###
@id=1
GET {{HotelListing.Api_HostAddress}}/api/countries

###

POST {{HotelListing.Api_HostAddress}}/api/countries
Content-Type: application/json

{
  "name": "Test Country",
  "shortname": "TC"
}

###

DELETE {{HotelListing.Api_HostAddress}}/api/countries/{countryid}

###


GET {{HotelListing.Api_HostAddress}}/api/countries/{{countryid}}

###

@countryid=1
PUT {{HotelListing.Api_HostAddress}}/api/countries/{{countryid}}
Content-Type: application/json

{
  "countryid": 1,
  "name": "Jamaica",
  "shortname": "JM"
}

###

GET {{HotelListing.Api_HostAddress}}/api/hotels

###

POST {{HotelListing.Api_HostAddress}}/api/hotels
Content-Type: application/json

{
  "Name": "Test Hotel",
  "Address": "123 Main St",
  "Rating": 4.5,
  "CountryId": 1
}

###
@id=1
DELETE {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}

###

GET {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}

###

PUT {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}
Content-Type: application/json

{
  "Id": 1,
  "Name": "Ocean Coral",
  "Address": "Trelawny, Jamacia",
  "Rating": 4.5,
  "CountryId" : 1
}

###


